/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author ikera
 */
public class MenuPropietario extends javax.swing.JFrame {

    /**
     * Creates new form MenuPropietario
     */
    public MenuPropietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaLocales = new javax.swing.JButton();
        Contestacion = new javax.swing.JButton();
        Valoraciones = new javax.swing.JButton();
        AgregarLocal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        CuentaMenu = new javax.swing.JMenu();
        CambiarDatos = new javax.swing.JMenuItem();
        EliminarCuenta = new javax.swing.JMenuItem();
        SesionMenu = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaLocales.setText("Lista Locales");
        ListaLocales.setActionCommand("");

        Contestacion.setText("Dar Contestaciones");
        Contestacion.setActionCommand("");
        Contestacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContestacionActionPerformed(evt);
            }
        });

        Valoraciones.setText("Valoraciones");
        Valoraciones.setActionCommand("");
        Valoraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValoracionesActionPerformed(evt);
            }
        });

        AgregarLocal.setText("Agregar Local");
        AgregarLocal.setActionCommand("");
        AgregarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLocalActionPerformed(evt);
            }
        });

        CuentaMenu.setText("Cuenta");

        CambiarDatos.setText("Cambiar Datos");
        CuentaMenu.add(CambiarDatos);

        EliminarCuenta.setText("Eliminar Cuenta");
        CuentaMenu.add(EliminarCuenta);

        jMenuBar1.add(CuentaMenu);

        SesionMenu.setText("Sesión");

        CerrarSesion.setText("Cerrar Sesión");
        SesionMenu.add(CerrarSesion);

        jMenuBar1.add(SesionMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgregarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contestacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contestacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContestacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContestacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContestacionActionPerformed

    private void AgregarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarLocalActionPerformed

    private void ValoracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValoracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValoracionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLocal;
    private javax.swing.JMenuItem CambiarDatos;
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JButton Contestacion;
    private javax.swing.JMenu CuentaMenu;
    private javax.swing.JMenuItem EliminarCuenta;
    private javax.swing.JButton ListaLocales;
    private javax.swing.JMenu SesionMenu;
    private javax.swing.JButton Valoraciones;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
